# Generated by Django 5.0.6 on 2024-06-12 16:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Имя и фамилия')),
                ('about', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2048, message='Максимум 2048 символов')], verbose_name='Обо мне')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='Минимальный возраст 18'), django.core.validators.MaxValueValidator(120, message='Максимальное возраст 120')], verbose_name='Возраст')),
                ('experience_year', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Минимальный опыт 0'), django.core.validators.MaxValueValidator(100, message='Максимальный опыт 100')], verbose_name='Опыт работы')),
                ('contact', models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='Минимально 10 символов'), django.core.validators.MaxLengthValidator(15, message='Максимально 15 символов')], verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
                'ordering': ['initials'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='Минимум 1 символ'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Название каталога')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='drf_task.employee', verbose_name='Владелец каталога')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
                'db_table': 'catalog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='Минимум 1 символ'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Название продукта')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2048, message='Максимум 2048 символов')], verbose_name='Описание продукта')),
                ('price', models.IntegerField(verbose_name='Цена продукта')),
                ('duration', models.DurationField(verbose_name='Продолжительность работы')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='drf_task.catalog', verbose_name='Каталог продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
    ]
